spring:
  messages:
    basename: "i18n/bundle"
    encoding: "UTF-8"

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

server:
  port: 8080

application:
  locale: en

questionnaire:
  csv-file-name:  "questions_${application.locale}.csv"
  min-right-answers: 1